name: ALL ABOUT WM
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
color:
  saturation: 0.597789
  brandStrength: 0.981203
  lightness: 0.384498
  brandColors:
    - '#1E1816'
    - '#FC652F'
    - '#E9E1DF'
    - '#ACA4A2'
    - '#655D5B'
  rhythmicContrast: 0.574658
typography_spectrum: 0.7814178
cta: {}
analytics: {}
layout_spectrum: 0.3528464
