cta: {}
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
opengraph: {}
color:
  saturation: 0.597789
  brandStrength: 0.981203
  lightness: 0.384498
  brandColors:
    - '#FFFFFF'
    - '#D00331'
    - '#676B6E'
    - '#D6D7D9'
    - '#8F9093'
  rhythmicContrast: 0.574658
typography_spectrum: 0.7814178
layout_spectrum: 0.9994629
analytics: {}
name: ALL ABOUT WM
