name: ALL ABOUT WM
purpose: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
opengraph: {}
color:
  rhythmicContrast: 0.574658
  brandStrength: 0.981203
  saturation: 0.597789
  brandColors:
    - '#F0E8E8'
    - '#C00830'
    - '#707878'
    - '#D80030'
    - '#E890A8'
  lightness: 0.384498
typography_spectrum: 0.7814178
cta: {}
analytics: {}
layout_spectrum: 0.3528464
